destination:        ./docs
title:              PipeRider
email:              your-email@example.com
description:        Data Reliability Automated
author:             PipeRider
company:            InfuseAI
company_url:        http://infuseai.io
baseurl:            ""
url:                https://daveflynn.github.io
domain:             daveflynn.github.io

# Social Profiles
twitter_username:   infuseai
github_username:    infuseai
facebook_username:  infuseai
instagram_username: 
linkedin_username:  infuseai

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           9
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-youtube
  - jekyll-seo-tag